### PR TITLE
Use --collection in refresh_modules command

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Pull request merged**
