### PR TITLE
Prep amazon.cloud 0.3.0

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Prep amazon.cloud 0.3.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by gravesm — COMMENTED** [review]
Should https://github.com/ansible-collections/amazon.cloud/pull/49/files#diff-6d334f222f8b3eaccfc01ec82248c174448c457c70a161ffd1255fd1439a5b9eL68 be `0.3.0`?

**Comment by alinabuzachis** [comment]
> Should https://github.com/ansible-collections/amazon.cloud/pull/49/files#diff-6d334f222f8b3eaccfc01ec82248c174448c457c70a161ffd1255fd1439a5b9eL68 be `0.3.0`?

Fixed, thanks!

**Review by gravesm — APPROVED** [review]

**Review by jillr — APPROVED** [review]
We should be able to remove the sanity ignore files for ansible-core<2.11, but IMO that can be a follow up PR to the collection

**Comment by alinabuzachis** [comment]
> We should be able to remove the sanity ignore files for ansible-core<2.11, but IMO that can be a follow up PR to the collection

Sure, will open follow up PR for that. Thanks

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Pull request merged**
