### PR TITLE
Add docs validation workflows

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Generate diffs and artefacts when someone pushes a docs PR.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

.github

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by gravesm** [comment]
I'm not sure I understand the status of this. Can you explain what is needed to get the CI to pass? I'd strongly prefer we not merge a change that is going to make it so we have to force merge over broken CI on every PR.

**Comment by alinabuzachis** [comment]
> I'm not sure I understand the status of this. Can you explain what is needed to get the CI to pass? I'd strongly prefer we not merge a change that is going to make it so we have to force merge over broken CI on every PR.

I reproduced the same thing tremble did for community.aws https://github.com/ansible/ansible-zuul-jobs/pull/1587#issuecomment-1177305689 This doesn't require us to copy doc fragments in the amazon.cloud collection.
Didn't add the galaxy importer things, not sure if we need them now. I can add those if needed.

**Comment by gravesm** [comment]
I think we need to add it, because we can't merge a PR that is going to perpetually break CI.

**Review by gravesm — APPROVED** [review]

**Pull request merged**
