### PR TITLE
Add rendered Changelog to the docs site

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

Requires https://github.com/ansible-collections/amazon.cloud/pull/26

Add rendered Changelog to the docs site

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
This has been tested merging the change into my fork's main and opening this PR https://github.com/alinabuzachis/amazon.cloud/pull/4

**Comment by alinabuzachis** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Review by jillr — APPROVED** [review]

**Pull request merged**
