### PR TITLE
Move api_specifications from the code generator to the respective collections

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by alinabuzachis — COMMENTED** [review]
@GomathiselviS @goneri Instead of manually doing this, why don't we automatically copy over these files  when a new release is prepared with the generator tool?

**Review by goneri — APPROVED** [review]

**Comment by goneri** [comment]
@alinabuzachis We would like to ultimately remove the amazon_cloud_code_generator. The code code base will move in gouttelette and be used also by vmware_rest_code_generator. Everything that is collection specific (e.g the list of modules that want to generate, the Jinja2 templates, these API specification files, etc) will end-up in a directory of the collection. This directory won't be included in the released content.

**Comment by goneri** [comment]
@GomathiselviS I'm fixing tox-cloud-refresh-examples-amazon.

**Comment by goneri** [comment]
recheck

**Comment by alinabuzachis** [comment]
> @alinabuzachis We would like to ultimately remove the amazon_cloud_code_generator. The code code base will move in gouttelette and be used also by vmware_rest_code_generator. Everything that is collection specific (e.g the list of modules that want to generate, the Jinja2 templates, these API specification files, etc) will end-up in a directory of the collection. This directory won't be included in the released content.

@goneri Yes, I know that, but I was thinking that the api specification files should initially live in the generator repo (whatever it would be), since they are dynamically generated on every run of the generator (this was my understanding). With the next release, these api specifications will be copied over into the amazon.cloud collection and propagated in the new release, am I wrong? If you think it sensible having them right now, I'm not +1 for merging this PR.

**Comment by alinabuzachis** [comment]
I guess we can close this one since api specifications live in gouttelette already.

**Pull request closed without merging**
