### PR TITLE
Update README to point gouttelette

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1770

Update README to point gouttelette

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Review by mandar242 — APPROVED** [review]

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
regate

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
recheck

**Pull request merged**
